#Create a note
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "A note by John Doe",
    "important": true,
    "userId": "612f6b38b04c9907e0fb3041"
}

###
#Create a note with no content
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "",
    "important": true
}