#Create a note
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "An api call tested with REST VSCode Plugin + MongoDB",
    "important": true
}

###
#Create a note with no content
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "",
    "important": true
}